# Generated by Django 3.1.2 on 2020-10-21 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_auto_20201020_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordX', models.FloatField()),
                ('coordY', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MasterObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.category')),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='masters.location')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.master')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('master_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.masterobject')),
            ],
        ),
    ]
