# Generated by Django 3.1.2 on 2020-10-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_location_masterobject_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterobject',
            name='category',
        ),
        migrations.AddField(
            model_name='masterobject',
            name='category',
            field=models.ManyToManyField(to='masters.Category'),
        ),
    ]
