# Generated by Django 3.1.2 on 2020-10-21 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_auto_20201021_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterobject',
            name='category',
        ),
        migrations.AddField(
            model_name='masterobject',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.category'),
        ),
    ]
